implement record keyword
ReactiveBayes/ExponentialFamilyProjection.jl pull request #11
Opened 2024-06-28 13:13 UTC by Nimrais

This PR adds a record keyword to `project_to` that is passed `gradient_descent!` inside to record cost values.

A new test added that cost is actually decreasing trough iterations.

2024-07-01 13:31 UTC, bvdmitri requested changes

2024-07-01 13:31 UTC, bvdmitri commented on src/projected_to.jl
> +    record = missing
I think at this point it makes sense to do something like 
```julia
function project_to(
    prj::ProjectedTo,
    f::F,
    supplementary...;
    initialpoint = nothing,
    kwargs...
) where {F}
```
and then 
```julia
q = gradient_descent!(
    M,
    objective,
    initialpoint;
    stopping_criterion = get_stopping_criterion(parameters),
    stepsize = getstepsize(parameters),
    direction = BoundedNormUpdateRule(static(1)),
    kwargs...
)
```

In the documentation we should note, that all extra keyword arguments are simply redirected to the `gradient_descent` call. You can actually see that `Manopt` [does the same](https://github.com/JuliaManifolds/Manopt.jl/blob/5062ad577e2bbc9dbcef156b702a769cf5a77b93/src/solvers/gradient_descent.jl#L228).

2024-07-01 13:31 UTC, bvdmitri commented on test/projection/projected_to_tests.jl
> +        @test all(map((before, after) ->  before > after, record[1:end-1], record[2:end]))
you can use `diff` for this operation

2024-07-01 13:31 UTC, bvdmitri commented on test/projection/projected_to_tests.jl
> +        approximated_2 = project_to(prj, targetfn_2)
you forgot to use `record = record` here so it actually does not test it here, but instead tests the previous case one more time

2024-07-01 13:35 UTC, bvdmitri commented on test/projection/projected_to_tests.jl
> +        @test all(map((before, after) ->  before > after, record[1:end-1], record[2:end]))
wait how does it even work? it shouldn't work since `record` does only have 1 value `[RecordCost()]`, so I guess the test does not test anything

2024-07-01 13:41 UTC, bvdmitri commented on test/projection/projected_to_tests.jl
> +        @test all(map((before, after) ->  before > after, record[1:end-1], record[2:end]))
@Nimrais I fixed the tests, they indeed didn't test the actual cost, because you were supposed to use the `recorded_values` field. See [here](https://github.com/ReactiveBayes/ExponentialFamilyProjection.jl/pull/11/commits/640b2a00d23762af695ebb6aa605505f37ee30d5)

2024-07-01 13:49 UTC, Nimrais commented on test/projection/projected_to_tests.jl
> +        @test all(map((before, after) ->  before > after, record[1:end-1], record[2:end]))
ahh I thought I fixed it, yeah you are obsoletely right.

2024-07-01 13:53 UTC, Nimrais commented on src/projected_to.jl
> +    record = missing
Ok and just update docstring to read about this kwargs in `Manopt.jl`

2024-07-01 13:54 UTC, Nimrais commented on src/projected_to.jl
> +    record = missing
Because from the point of user it's not obvious what they can actually pass here.

2024-07-01 14:54 UTC, Nimrais commented on src/projected_to.jl
> +    record = missing
I have exteneded `project_to` method documentation, you can check. I think it's delivering what we have discussed here.

2024-07-02 08:50 UTC, bvdmitri approved these changes
Thanks @Nimrais !

2024-07-02 08:50 UTC, merged