Direction rule as argument to projection parameters
ReactiveBayes/ExponentialFamilyProjection.jl pull request #31
Opened 2024-08-02 15:25 UTC by ismailsenoz

This small PR makes direction update rule argument to `ProjectionParameters` structures, so that we can manipulate the scale of `BoundedNormUpdateRule` or test with other rules from manopt.

2024-08-02 15:36 UTC, Nimrais approved these changes

2024-08-02 15:37 UTC, Nimrais requested changes
Yeah, that's fine. But we just need to add a simple test to merge it first.

2024-08-05 09:40 UTC, Nimrais commented
I made several changes to the PR.

Adds three key tests: one demonstrating the effectiveness of BoundedNormUpdateRule for Maximum Likelihood Estimation across multiple distributions, by increasing bound norm it's possible to improve results.

And two showcasing the MomentumGradient update rule with both logpdf functions and sample data.

2024-08-05 09:46 UTC, Nimrais approved these changes

2024-08-05 09:54 UTC, albertpod commented
Generally, I think it's a good PR, guys. @Nimrais, thanks for the additional tests, they make the intention of the change clear.

For the future, let's strive to have tests that explicitly test the added feature. The first test from [1b0df2b](https://github.com/ReactiveBayes/ExponentialFamilyProjection.jl/pull/31/commits/1b0df2b362372e3894761d52c5078e0367389a8a) wasn't particularly clear to me.

2024-08-05 09:54 UTC, albertpod approved these changes

2024-08-05 09:55 UTC, merged