fead(breaking): update to Manopt 0.5
ReactiveBayes/ExponentialFamilyProjection.jl pull request #40
Opened 2024-10-28 12:30 UTC by Nimrais

2024-11-06 09:19 UTC, bvdmitri requested changes
I would use new API from Manopt where we no longer need to pass manifold as an argument + tests are failing

2024-11-06 09:19 UTC, bvdmitri commented on test/projection/projected_to_tests.jl
> +    direction = Manopt.MomentumGradientRule(manifold; p=initialpoint)
I think the new Manopt doesn't require `manifold` as an argument? I think we can use the better improved API

2024-11-06 12:09 UTC, Nimrais commented
> I would use new API from Manopt where we no longer need to pass manifold as an argument + tests are failing

It's magically fixed in 1.11.1, it's smt inside Manopt.jl they have some type instability.

2024-11-21 16:23 UTC, bvdmitri approved these changes

2024-11-21 16:23 UTC, bvdmitri commented on test/projection/projected_to_tests.jl
> +    @show typeof(projection.parameters.direction)
```suggestion
```

2024-11-21 20:15 UTC, merged